#!/bin/bash
# make clean
make

./Legalizer Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_16900.lg Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_16900.opt testcase1_16900_post.lg
# time ./Legalizer Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_ALL0_5000.lg Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_ALL0_5000.opt testcase1_ALL0_5000_post.lg
# time ./Legalizer Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_MBFF_LIB_7000.lg Optimizer-and-Legalizer-Co-optimization/testcase/testcase1_MBFF_LIB_7000.opt testcase1_MBFF_LIB_7000_post.lg
# time ./Legalizer Optimizer-and-Legalizer-Co-optimization/testcase/testcase2_100.lg Optimizer-and-Legalizer-Co-optimization/testcase/testcase2_100.opt testcase2_100_post.lg
